[default.general]
chip = "STM32F405RGTx"
log_level = "INFO"

[default.rtt]
enabled = true

[default.gdb]
# Whether or not a GDB server should be opened after flashing.
enabled = true
# The connection string in host:port format wher the GDB server will open a socket.
gdb_connection_string = "127.0.0.1:1337"
